version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "2222:22"
    command: user:pass:::temporary_data,production

  redis:
    image: redis
    container_name: redis_server
    ports:
      - "6379:6379"
